# cook your dish here
t=int(input())
for i in range(t):
    n=int(input())
    c=n%4
    if c>=2:
        print("yes")
    else:
        print("No")
        
        
        
        
        
        
        
        
        
        
        
t = int(input())
for i in range(t):
    n = int(input())
    if(n%4 == 0):
        print("NO")
    else:
        print("YES")
        
        
        
        
        
        
        
        
        
        
        
# cook your dish here
for i in range(int(input())):
    n=int(input())
    if(n%4==0):
        print("NO")
    else:
        a=n%4
        if(n%2==0):
            print("YES")
            
            
            
            
            
            
            
            
# cook your dish here
for i in range(int(input())):
        n=int(input())
        print("YES") if n%4!=0 else print("NO")