# cook your dish her
t=int(input())
for i in range(t):
    x=int(input())
    if x>65:
        print("overload")
    elif x<35:
        print("underload")
    else:
        print("Normal")
        
        
        
        
        
        
        
        
        
        
# cook your dish here
for i in range(int(input())):
    x=int(input())
    if(x>65):
        print("Overload")
    elif(x<35):
        print("Underload")
    else:
        print("Normal")
        
        
        
        
        
# cook your dish here
for i in range(int(input())):
    x=int(input())
    if x>65:
        print('Overload')
    elif x<35:
        print('Underload')
    else:
        print('Normal')
        
        
        
        
        
        
        
# cook your dish here
for i in range(int(input())):
        x=int(input())
        if x>65:
                print("OVERLOAD")
        elif x<35:
                print("UNDERLOAD")
        else:
                print("NORMAL")
                
                
                
                
                
                
                
# cook your dish here
for i in range(int(input())):
        x=int(input())
        if x>65:
                print("OVERLOAD")
        elif x<35:
                print("UNDERLOAD")
        else:
                print("NORMAL")