# cook your dish here
t=int(input())
for i in range(t):
    x=int(input())
    print(7-x)
    
    
    
    
    
    
    
    
    
    
    
# cook your dish here
for i in range(int(input())):
    x=int(input())
    print(7-x)
    
    
    
# cook your dish here
for i in range(int(input())):
        x=int(input())
        print(7-x)
        
        
        
        
        
        
#include <iostream>
using namespace std;

int main() {
    int T;
    cin>>T;
    while(T--){
        int a;
        cin>>a;
        cout<<(7-a)<<endl;
    }
	// your code g{oes here
	return 0;
}
 
 
 
 
 
 
 
 
#include <iostream>
using namespace std;

int main() {
    int t;
    cin>>t;
    while(t--){
        int x;
        cin>>x;
        cout<<7-x<<endl;
    }
	// your code goes here
	return 0;
}
