t = int(input())
for i in range(t):
    a,b,c = map(int, input().split())
    s=a+b+c
    if(s>=6):
        print("yes")
    else:
        print("no")
        
        
        
        
        
        
        
        
        
        
        
        
# cook your dish here
for i in range(int(input())):
  X,Y,Z = map(int,input().split())
  if (X+Y+Z) >= 6:
    print("YES")
  else:
    print("NO")
    
    
    
    
    
    
    
    
    
    
    
# cook your dish here
a = int(input())
for i in range(a):
    b,c,d = map(int, input().split())
    if b+c+d >= 6 :
        print("yes")
    else:
        print("no")
        
        
        
        
        
        
        
        
        
        
for i in range(int(input())):
    x,y,z=map(int,input().split())
    if((x+y+z)>=6):
        print("YES")
    else:
        print("NO")
        
        