# cook your dish here
dic = {'b':'BattleShip', 'c':'Cruiser', 'd':'Destroyer', 'f':'Frigate'}
for i in range(int(input())):
    print(dic[input().lower()])
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
T = int(input())
for i in range(T):
    s = input()
    if s == 'B' or s == 'b':
        print('BattleShip')
    elif s == 'F' or s == 'f':
        print('Frigate')
    elif s == 'C' or s == 'c':
        print('Cruiser')
    else:
        print('Destroyer')
        
        
        
        
        
        
        
        
        
        
        
# cook your dish here
a=int(input())
for i in range(a):
    b=input()
    if b.upper()=="B":
        print("BattleShip")
    elif b.upper()=="C":
        print("Cruiser")
    elif b.upper()=="D":
        print("Destroyer")
    else:
        print("Frigate")
        
        
        
        
        
        
        
        
        
        
        
        
        
# cook your dish here
dic = {'b':'BattleShip', 'c':'Cruiser', 'd':'Destroyer', 'f':'Frigate'}
for i in range(int(input())):
    print(dic[input().lower()])
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
# cook your dish here
T=int(input())
for i in range(T):
    X=input()
    if X=='B' or X=='b':
        print('BattleShip')
    if X=='C' or X=='c':
        print('Cruiser')
    if X=='D' or X=='d':
        print('Destroyer')
    if X=='F' or X=='f':
        print('Frigate')  
    
    