# cook your dish here
x=list(map(int,input().split()))
a=x[0]
x.remove(a)
if(a in x):
    print("YES")
else:
    print("NO")
    
    
    
    
    
    
    
    
    
    
    
# cook your dish here
# cook your dish here
x=list(map(int,input().split()))
a=x[0]
x.remove(a)
if(a in x):
    print("YES")
else:
    print("NO")
    
    
    
    
    
    
    
    
    
    
    
    
    
    
# cook your dish here
A,B,C = map(int,input().split())
if A==B or B==C or C==A:
  print("YES")
else:
  print("No")
  
  
  
  
  
  
  
# cook your dish here
a,b,c=map(int,input().split())
if(a==b and b==c):
    print("yes")
elif(a==b or b==c or a==c):
    print("yes")
else:
    print("no")