for _ in range(int(input())):
    x,y,z = map(int,input().split())
    if (x + y) < z:
        print('PLANEBUS')
    elif (x + y) > z:
        print('TRAIN')
    else: print('EQUAL')
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
# # cook your dish here
t=int(input())
for i in range (t):
    X,Y,Z=map(int, input().split())
    if (X+Y)>Z:
        print('Train')
    elif (X+Y)<Z:
        print('PlaneBus')
    else:
        print('Equal')
        
        
        
        
        
        
        
        
        
        
# # cook your dish here
t=int(input())
for i in range (t):
    X,Y,Z=map(int, input().split())
    if (X+Y)>Z:
        print('Train')
    elif (X+Y)<Z:
        print('PlaneBus')
    else:
        print('Equal')
        
        
        
        
        
        
        
        
        
        
# cook your dish here
for i in range(int(input())):
  X,Y,Z = map(int,input().split())
  if Z < X+Y:
    print("TRAIN")
  elif Z > X+Y:
    print("PLANEBUS")
  else:
    print("EQUAL")
    
    
    
    
    
    
    
    
# cook your dish here
for i in range(int(input())):
  X,Y,Z = map(int,input().split())
  if Z < X+Y:
    print("TRAIN")
  elif Z > X+Y:
    print("PLANEBUS")
  else:
    print("EQUAL")