for i in range(int(input())):
    x=int(input())
    if x in range(1,100):print('Easy')
    elif x in range(100,200):print('Medium')
    else:print('Hard')
    
    
    
    
    
    
    
# cook your dish here
t=int(input())
for i in range(t):
    n=int(input())
    if(n>=1 and n<100):
        print("Easy")
    elif(n>=100 and n<200):
        print("Medium")
    else:
        print("Hard")
        
        
        
        
        
        
        
        
        
        
# cook your dish here
for t in range(int(input())):
    x = int(input())
    if x >= 1 and x < 100:
        print('Easy')
    elif x >= 100 and x < 200:
        print('Medium')
    elif x >= 200 and x <= 300:
        print('Hard')
        
        
        
        
        
        
        
# cook your dish here
for i in range(int(input())):
    x = int(input())
    
    if x>=1 and x<100:
        print("Easy")
    
    elif x>=100 and x<200:
        print("Medium")
    
    else:
        print("Hard")
        
        
        
        
        
        
        
        
        
        
        
        
# cook your dish here
for i in range(int(input())):
    x = int(input())
    
    if x>=1 and x<100:
        print("Easy")
    
    elif x>=100 and x<200:
        print("Medium")
    
    else:
        print("Hard")