for _testcase in range(int(input())):
    a,b = map(int, input().split())
    if a > 1000: print((a*b) - ((a*b)/100)*10)
    else: print((a*b))
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
for t in range(int(input())):
    qty, pr = map(float, input().split())
    total = qty * pr 
    print(total * .9 if qty > 1000 else total)
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
# cook your dish here
for i in range(int(input())):
        q,p=map(int,input().split())
        print(p*q) if q<1000 else print(p*q-(p*q*0.1))
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
# cook your dish here
for i in range(int(input())):
        q,p=map(int,input().split())
        print(p*q) if q<1000 else print(p*q-(p*q*0.1))
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
# cook your dish here
for i in range(int(input())):
        q,p=map(int,input().split())
        print(p*q) if q<1000 else print(p*q-(p*q*0.1))