for t in range(int(input())):
    r = int(input())
    if 2000 <= r:
        print("1")
    elif 1600 <= r and r <= 2000:
        print("2")
    elif r <= 1600:
        print("3")
        
        
        
        
        
        
t=int(input())
for i in range(t):
    x=int(input())
    if x>=2000:
        print("1")
    elif x<1600:
        print("3")
    else:
        print("2")
        
        
        
        
        
        
        
        
        
        
        
        
# cook your dish here
for _ in range(int(input())):
    n=int(input())
    if(n>=2000):
        print(1)
    elif(n>=1600 and n<2000):
        print(2)
    elif(n<1600):
        print(3)
            
            
            
            
            
            
            
            
            
            
            
        
# cook your dish here
for _ in range(int(input())):
    n=int(input())
    if(n>=2000):
        print(1)
    elif(n>=1600 and n<2000):
        print(2)
    elif(n<1600):
        print(3)
            
            
            
            
            
            
            
            
            
            
            
            
# cook your dish here
for i in range(int(input())):
  R = int(input())
  if R<1600:
    print("3")
  elif R>=1600 and R<2000:
    print("2")
  else:
    print("1")
    
    
    
    
    
            
