# cook your dish here
for _ in range(int(input())):
    n=int(input())
    print((n//2)+1)
    
    
    
    
    
    
    
    
    
    
    
# cook your dish here
for i in range(int(input())):
        n=int(input())
        print((n//2)+1)
        
        
        
        
        
        
        
        
        
        
        
#include <iostream>
using namespace std;

int main() { int t;
    cin>>t;
    while(t--)
    { int a;
        cin>>a;
        cout<<((a/2)+1)<<endl;
    }
}















#include <iostream>
using namespace std;

int main() { int t;
    cin>>t;
    while(t--)
    { int a;
        cin>>a;
        cout<<((a/2)+1)<<endl;
    }
}