t = int(input())
for _ in range(t):
    if(t >= 1 and t <= 5*(pow(10, 3))):
        g, c = map(int, input().split())
        if(g >= 1 and g <= 10 and c >= 1 and c <= 3000):
            x = (pow(c, 2)) / (2 * g)
            print(int(x))
            
            
            
            
            
            
            
# cook your dish here
for i in range(int(input())):
        g,c=map(int,input().split())
        print((c**2)//(2*g))
        
        
        
        
        
        
        
        
        
        
        
        
        
# cook your dish here
for i in range(int(input())):
  g,c = map(int,input().split())
  print((c*c)//(2*g))
  
  
  
  
  
  
  
  
  
  
  
  
  
# cook your dish here
for i in range(int(input())):
  g,c = map(int,input().split())
  print((c*c)//(2*g))