# cook your dish here
t = int(input())
for i in range(t):
    a,b,x = map(int,input().split())

    print((b-a)//x)
    
    
    
    
    
    
    
    
    
    
    
    
# cook your dish here
t = int(input())
for i in range(t):
    a,b,x = map(int,input().split())

    print((b-a)//x)
    
    
    
    
    
    
    
    
    
    
    
    
# cook your dish here
t=int(input())
for _ in range(t):
    a,b,x=map(int,input().split())
    k=b-a
    m=k//x
    print(m)
    
    
    
    
    
    
    
    
    
# cook your dish here
def check(a,b,x):
    return int((b-a)/x)

t=int(input())
for _ in range(t):
    a,b,x=map(int,input().split(' '))
    print(check(a,b,x))
    
    
    
    
    
    
    
    
    
    
    
    
    
    
# cook your dish here
for i in range(int(input())):
        a,b,x=map(int,input().split())
        print((b-a)//x)