# cook your dish here
years=[2010,2015,2016,2017,2019]
for _ in range(int(input())):
    year=int(input())
    if year in years:
        print('HOSTED')
    else:
        print('NOT HOSTED')
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
for t in range (int(input())):
    years = [2010, 2015, 2016, 2017, 2019]
    if int(input()) in years:
        print("HOSTED")
    else:
        print("NOT HOSTED")
        
        
        
        
        
        
        
        
        
        
        
# cook your dish here
t=int(input())
for i in range(t):
        n=int(input())
        k=[2010,2015,2016,2017,2019]
        print("HOSTED") if n in k else print("NOT HOSTED")
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
#include <iostream>
using namespace std;

int main() {
    int t;cin>>t;
    while (t--)
    {
        int n;cin>>n;
   if(n==2010||n==2015||n==2019||n==2016||n==2017)
        {
            cout<<"HOSTED"<<endl;
        }
        else
{
   cout<<"NOT HOSTED "<<endl;
}
    }
	// your code goes here
	return 0;
}

















#include <iostream>
using namespace std;

int main() {
	// your code goes here
	int q;
	cin>>q;
	while(q--)
	{
	    int a;
	    cin>>a;
	    if(a==2010||a==2015||a==2016||a==2017||a==2019)
	    {
	        cout<<"HOSTED"<<endl;
	    }
	    else
	    {
	        cout<<"NOT HOSTED"<<endl;
	    }
	}
	return 0;
}
//SUSHEEL PRAJAPATI (MEAN STACK DEVELOPER)