# cook your dish here
for _ in range(int(input())):
    n,m=map(int,input().split())
    print(m*n)
    
    
    
    
    
    
    
    
    
    
    
    
    
    
for t in range(int(input())):
    n, m = map(int, input().split())
    print(n * m)
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
# cook your dish here
for i in range(int(input())):
        n,m=map(int,input().split())
        print(n*m)
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
#include <stdio.h>

int main(void) {
    int t;
    scanf("%d",&t);
    while(t!=0)
    {
        int n,m;
        scanf("%d %d",&n,&m);
        printf("%d \n",(n*m));
        t--;
    }
	// your code goes here
	return 0;
}
