# cook your dish here
for _ in range(int(input())):
    a,b,c=map(int,input().split())
    print(max(a+c,b))
    
    
    
    
    
    
    
    
    
    
    
    
    
for t in range(int(input())):
    a, b, c = map(int, input().split())
    print(a + c if(a + c >= b) else b)
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
# cook your dish here
for i in range(int(input())):
        x,y,z=map(int,input().split())
        print(max(x+z,y))
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
