# cook your dish here
for _ in range(int(input())):
    am,bm,cm,t,a,b,c=map(int,input().split())
    if(a>=am and b>=bm and c>=cm and(a+b+c)>=t):
        print('YES')
    else:
        print('NO')
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
# cook your dish here
for i in range(int(input())):
    a,b,c,r,x,y,z=map(int,input().split())
    if((x+y+z)>=r and x>=a and y>=b and z>=c):
        print('YES')
    else:
        print('NO')
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
# cook your dish here
for i in range(int(input())):
    x,y,z,t,a,b,c=map(int,input().split())
    if(a>=x and b>=y and c>=z and (a+b+c)>=t):
        print("YES")
    else:
        print("NO")
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
# cook your dish here
for i in range(int(input())):
        x,y,z,m,a,b,c=map(int,input().split())
        print("YES") if (a>=x and b>=y and c>=z and a+b+c>=m) else print("NO")