t = input()
if len(t) == 1:
  print(1)
elif len(t) == 2:
  print(2)  
elif len(t) == 3:
  print(3) 
else:
  print("More than 3 digits")  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
x = input()
print(len(x) if len(x)<=3 else "More than 3 digits")













# cook your dish here
n=(input())
print(len(n)) if len(n)<=3 else print("More than 3 digits")

        