# cook your dish here
for t in range(int(input())):
    a,b=map(int,input().split())
    print(max(a,b),end=" ")
    print(a+b)
    
    
    
    
    
    
    
    
    
    
    
    
    
# cook your dish here
for t in range(int(input())):
    a,b=map(int,input().split())
    print(max(a,b),end=" ")
    print(a+b)
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
T = int(input())
for _ in range(T):
    A,B = map(int,input().split())
    print(max(A,B),(A+B))
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
T = int(input())
for _ in range(T):
    A,B = map(int,input().split())
    print(max(A,B),(A+B))
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
#include <iostream>
using namespace std;

int main()
{
    int t,a,b;
    cin>>t;
    while(t--)
    {
      cin>>a>>b;
      cout<<max(a,b)<<" "<<a+b<<endl;
    }
return 0;}


















# cook your dish here
for i in range(int(input())):
        a,b=map(int,input().split())
        print(max(a,b),a+b)