# cook your dish here
for i in range(int(input())):
    n=int(input())
    print((n//2)+1)
    
    
    
    
    
t = int(input())
for i in range(t):
    n=int(input())
    print((n//2)+1)
    
    
    
    
    
    
    
    
    
    
    
    
    
    
for _ in range(int(input())):
    print((1+int(input()))//2)
    
    
    
    
    
    
    
    
    
    
    
    
    
    
t = int(input())
while(t > 0):
    n = int(input())
    print(n//2 + 1)
    t -= 1