# cook your dish here
t=int(input())
for i in range(t):
    n,x=map(int,input().split())
    a=n//3 
    print(a//x)
    
    
    
    
    
# cook your dish here
t=int(input())
for _ in range(t):
    n,x=map(int,input("").split())
    a=n//x
    b=a//3
    print(b)
    
# cook your dish here
t=int(input())
for _ in range(t):
    n,x=map(int,input("").split())
    a=n//x
    b=a//3
    print(b)
    
    
# cook your dish here
for t in range(int(input())):
    n,x = map(int,input().split())
    print(int(n/(3*x)))
    
    
    
    
# cook your dish here
t=int(input())
for i in range(t):
    n,x=map(int,input().split())
    print(int(n/(x*3)))
    
    


