# We have populated the solutions for the 10 easiest problems for your support.
# Click on the SUBMIT button to make a submission to this problem.

#Note that it's python3 Code. Here, we are using input() instead of raw_input().
#You can check on your local machine the version of python by typing "python --version" in the terminal.

t=int(input())
for i in range(t):
	n=int(input())
	print(int(n**0.5))
 
 
 
 
 
# cook your dish here 
import math
for i in range(int(input())):
    n=int(input())
    a=math.sqrt(n)
    print(int(a))
    
    
    
    
# We have populated the solutions for the 10 easiest problems for your support.
# Click on the SUBMIT button to make a submission to this problem.

#Note that it's python3 Code. Here, we are using input() instead of raw_input().
#You can check on your local machine the version of python by typing "python --version" in the terminal.

import math
t=int(input())
for i in range(t):
	n=int(input())
	print(int(math.sqrt(n)))
 
 
 
 
 
 
 
# We have populated the solutions for the 10 easiest problems for your support.
# Click on the SUBMIT button to make a submission to this problem.

#Note that it's python3 Code. Here, we are using input() instead of raw_input().
#You can check on your local machine the version of python by typing "python --version" in the terminal.

import math
t=int(input())
for i in range(t):
	n=int(input())
	print(int(math.sqrt(n)))
 
 
 
 
 
 
# We have populated the solutions for the 10 easiest problems for your support.
# Click on the SUBMIT button to make a submission to this problem.

#Note that it's python3 Code. Here, we are using input() instead of raw_input().
#You can check on your local machine the version of python by typing "python --version" in the terminal.

import math
t=int(input())
for i in range(t):
	n=int(input())
	print(int(math.sqrt(n)))