# cook your dish here
t=int(input())
for i in range(t):
    n=int(input())
    a=list(map(int,input().strip().split()))
    print(max(a))
    
    
    
    
    
# cook your dish here
for _ in range(int(input())):
    n = int(input())
    
    print(max(map(int,input().split())))
    
    
    
    
# cook your dish here
for i in range(int(input())):
        n=int(input())
        na,nb,nc,nd=map(int,input().split())
        print(max(na,nb,nc,nd))
        
        
        # cook your dish here

t=int(input())
for i in range(t):
    n=int(input())
    a=list(map(int,input().split()))
    s=a.sort()
    print(a[3])
    
    
    
# cook your dish here

t=int(input())
for i in range(t):
    n=int(input())
    a=list(map(int,input().split()))
    s=a.sort()
    print(a[3])
    
    
# cook your dish here

t=int(input())
for i in range(t):
    n=int(input())
    a=list(map(int,input().split()))
    s=a.sort()
    print(a[3])
    
    
    

        
